import { useState, useEffect } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input"; // Added Input import
import { useToast } from "@/components/ui/use-toast"; // Added toast import
import ChatInterface from "./ChatInterface";
import AgentInterface from "./AgentInterface";
import {
  ArrowRight,
  Bell,
  Calendar,
  Lightbulb,
} from "lucide-react";
import { getGeminiResponse } from "../utils/geminiApi"; // Import AI agent API

const Dashboard = () => {
  const [activeTab, setActiveTab] = useState("agent");
  const [dailyPlan, setDailyPlan] = useState<any[]>([]);
  const [isFetchingPlan, setIsFetchingPlan] = useState(false); // Track AI plan fetching
  const [userInput, setUserInput] = useState(""); // User input for AI
  const { toast } = useToast();

  const handleGeneratePlan = async () => {
    if (!userInput.trim()) {
      toast({
        title: "Input required",
        description: "Please provide your idea or context to generate the plan.",
        variant: "destructive",
      });
      return;
    }

    setIsFetchingPlan(true);

    try {
      // Fetch the 10-day plan from the AI agent
      const response = await getGeminiResponse(
        userInput,
        "operations", // Specify the domain for the AI agent
        "10-day-plan", // Specify the output format
        false // Concise mode is false for detailed plans
      );

      if (!response || !response.structuredOutput) {
        throw new Error("Failed to fetch the plan from the AI agent.");
      }

      // Reformat the plan into a structured format
      const detailedPlan = response.structuredOutput.map((day: any, index: number) => ({
        day: index + 1,
        content: `Day ${index + 1}:\n\nHighlights:\n${day.highlights
          ?.map((highlight: string, i: number) => `${i + 1}. ${highlight}`)
          .join("\n") || "No highlights provided."}\n\nTasks:\n${day.tasks
          ?.map((task: string, i: number) => `${String.fromCharCode(65 + i)}. ${task}`)
          .join("\n") || "No tasks provided."}`,
      }));

      setDailyPlan(detailedPlan); // Set the AI-generated plan
      toast({
        title: "Plan generated",
        description: "Your 10-day plan has been successfully generated by the AI agent.",
      });
    } catch (error) {
      console.error("Error fetching plan:", error);
      toast({
        title: "Error",
        description: "Failed to fetch the plan from the AI agent. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsFetchingPlan(false);
    }
  };

  const renderDailyPlanSection = () => (
    <div className="mt-6 border rounded-lg p-4 bg-blue-50/50">
      <h3 className="text-lg font-medium mb-3">10-Day Detailed Plan</h3>
      <div className="mb-4">
        <Input
          placeholder="Enter your idea or context to generate the plan"
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          disabled={isFetchingPlan || dailyPlan.length > 0}
        />
        <Button
          onClick={handleGeneratePlan}
          className="mt-2"
          disabled={isFetchingPlan || !userInput.trim() || dailyPlan.length > 0}
        >
          {isFetchingPlan ? "Fetching Plan..." : "Generate 10-Day Plan"}
        </Button>
      </div>
      {dailyPlan.length > 0 && (
        <div className="space-y-4">
          {dailyPlan.map((day) => (
            <div key={day.day} className="border-b pb-3">
              <h4 className="font-medium text-primary">Day {day.day}</h4>
              <p className="text-sm whitespace-pre-line">{day.content}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">Welcome to Your Dashboard</h1>

      <Tabs
        defaultValue="agent"
        value={activeTab}
        onValueChange={setActiveTab}
        className="space-y-8"
      >
        <TabsList>
          <TabsTrigger value="agent">AI Agent</TabsTrigger>
          <TabsTrigger value="chat">Chat Assistant</TabsTrigger>
          <TabsTrigger value="insights">Business Insights</TabsTrigger>
          <TabsTrigger value="calendar">10-Day Plan</TabsTrigger> {/* Replaced Calendar */}
        </TabsList>

        {/* Agent Tab */}
        <TabsContent value="agent" className="space-y-6 focus:outline-none">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-3">
              <AgentInterface />
            </div>
          </div>
        </TabsContent>

        {/* Chat Tab */}
        <TabsContent value="chat" className="space-y-6 focus:outline-none">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2">
              <ChatInterface />
            </div>

            <div className="space-y-6">
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle>Suggested Actions</CardTitle>
                  <CardDescription>Based on recent conversations</CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-3">
                    <li>
                      <ActionItem
                        icon={<Bell className="h-4 w-4" />}
                        title="Review competitor analysis"
                        description="Complete marketing strategy update"
                        time="2 days ago"
                        priority="high"
                      />
                    </li>
                    <li>
                      <ActionItem
                        icon={<Calendar className="h-4 w-4" />}
                        title="Schedule investor meeting"
                        description="Prepare pitch deck for Series A"
                        time="1 day ago"
                        priority="medium"
                      />
                    </li>
                    <li>
                      <ActionItem
                        icon={<Lightbulb className="h-4 w-4" />}
                        title="Analyze user feedback"
                        description="Prioritize roadmap features"
                        time="Just now"
                        priority="low"
                      />
                    </li>
                  </ul>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle>Recent Insights</CardTitle>
                  <CardDescription>Generated from your data</CardDescription>
                </CardHeader>
                <CardContent>
                  <InsightItem
                    title="Conversion Rate Increased"
                    value="+12%"
                    trend="up"
                    description="Your recent landing page change is performing well"
                  />
                  <InsightItem
                    title="Customer Acquisition Cost"
                    value="-8%"
                    trend="up"
                    description="Facebook ads optimization is working"
                  />
                  <div className="mt-4">
                    <Button variant="link" className="p-0 h-auto flex items-center">
                      View all insights
                      <ArrowRight className="ml-1 h-3.5 w-3.5" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </TabsContent>

        {/* Insights Tab */}
        <TabsContent value="insights" className="focus:outline-none">
          {/* TODO: Add Insights tab content here */}
          <p>Insights feature coming soon...</p>
        </TabsContent>

        {/* 10-Day Plan Tab */}
        <TabsContent value="calendar" className="focus:outline-none">
          {renderDailyPlanSection()}
        </TabsContent>
      </Tabs>
    </div>
  );
};

interface ActionItemProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  time: string;
  priority: "high" | "medium" | "low";
}

const ActionItem = ({
  icon,
  title,
  description,
  time,
  priority,
}: ActionItemProps) => {
  return (
    <div className="flex items-start space-x-3 p-3 border rounded-md bg-muted">
      <div className="text-muted-foreground">{icon}</div>
      <div className="flex-1">
        <div className="font-medium">{title}</div>
        <div className="text-sm text-muted-foreground">{description}</div>
        <div className="text-xs text-gray-400 mt-1">
          {time} • Priority: {priority}
        </div>
      </div>
    </div>
  );
};

interface InsightItemProps {
  title: string;
  value: string;
  trend: "up" | "down";
  description: string;
}

const InsightItem = ({
  title,
  value,
  trend,
  description,
}: InsightItemProps) => {
  return (
    <div className="mb-4">
      <div className="flex justify-between">
        <div className="font-medium">{title}</div>
        <div
          className={`font-semibold ${
            trend === "up" ? "text-green-500" : "text-red-500"
          }`}
        >
          {value}
        </div>
      </div>
      <div className="text-sm text-muted-foreground">{description}</div>
    </div>
  );
};

export default Dashboard;
